import time
import motion_list

def motion_test():
    time.sleep(2)
    print('init')
    motion_list.m_init()
    time.sleep(5)
    
    print('question')
    motion_list.m_question()
    time.sleep(5)
    
    print('suggestion')
    motion_list.m_suggestion()
    time.sleep(2)
    
    print('explain')
    motion_list.m_explain()
    time.sleep(2)
    motion_list.m_photo()
    time.sleep(2)
    motion_list.m_stamp()
    time.sleep(2)
    motion_list.m_waiting()
    time.sleep(2)
    motion_list.m_cheer()
    time.sleep(2)
    motion_list.m_compliment()
    time.sleep(2)
    motion_list.m_concil()
    time.sleep(2)
    motion_list.m_search()
    time.sleep(2)
    motion_list.m_sleep()
    time.sleep(2)
    motion_list.m_wakeup()
    time.sleep(2)
    motion_list.m_agree()
    time.sleep(2)
    motion_list.m_deny()
    time.sleep(2)
    motion_list.m_joy()
    time.sleep(2)
    motion_list.m_angry()
    time.sleep(2)
    motion_list.m_sad()
    time.sleep(2)
    motion_list.m_tired()
    time.sleep(2)
    
if __name__ == '__main__':
    motion_test()
    time.sleep(2)
